// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPe8ji9fsyIADdeHkGNRoIm-FSsxKYT-8',
    appId: '1:791942755799:web:c6203456c4bdb631600792',
    messagingSenderId: '791942755799',
    projectId: 'nottechat',
    authDomain: 'nottechat.firebaseapp.com',
    storageBucket: 'nottechat.firebasestorage.app',
    measurementId: 'G-CGC4BJJJME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNujgmPFzMVVCY9PdKwEpTSBOZhCeeK4A',
    appId: '1:791942755799:android:b11a2ccfbf870aee600792',
    messagingSenderId: '791942755799',
    projectId: 'nottechat',
    storageBucket: 'nottechat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FtE3U6au9h7f0hRydshYb4JGEz7Lv9c',
    appId: '1:791942755799:ios:8202936d61fadeb4600792',
    messagingSenderId: '791942755799',
    projectId: 'nottechat',
    storageBucket: 'nottechat.firebasestorage.app',
    iosClientId: '791942755799-v239un74c3hd96lqvvdeljkc4hn1ummh.apps.googleusercontent.com',
    iosBundleId: 'com.nottechat.ai',
  );
}
